### ISSUE TITLE
Export: Add option to remove `entry Id` and `ary details`

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/client#1484]
Labels:
1. Show entry ID
2. Show Assessments details

Send these as export options.

**Comment by subinasr** [comment]
![image.png](https://zube.io/files/deep/fc9b1ebad9a1bf256e1d52f0b4590ea9-image.png)

@jbbove After the requested changes, this is what the export selection looks like.

**Comment by jbbove** [comment]
I see thanks @Subina-Sharma-Rajopadhyaya . It looks even more complex than before so I am a bit worried. Will these changes only be applied to the GIMAC project or to all exports?

**Comment by AdityaKhatri** [comment]
@jbbove , they will be applied to all the projects and this is something they required for IMMAP.

**Comment by jbbove** [comment]
Ok.
@AdityaKhatri let's deploy as is since the taggers need it. But we are adding complexity to the UX, this will need to be reviewed and changed at some point... For example if the Additional Metadata boxe is unticked, then the Additional Metadata line should disappear. Also what is the default behaviour? Are all the boxes ticked by default?

**Comment by AdityaKhatri** [comment]
@jbbove , we've introduced that behavior.
Did you get time to play around with this?
Let us know what you think.
